// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_full_circle = "CgkIm_nTr7sPEAIQBA"; // <GPGSID>
        public const string leaderboard_most_epic_journey = "CgkIm_nTr7sPEAIQAg"; // <GPGSID>
        public const string achievement_the_beautiful_night_sky = "CgkIm_nTr7sPEAIQBw"; // <GPGSID>
        public const string achievement_expanded_consciousness = "CgkIm_nTr7sPEAIQBg"; // <GPGSID>
        public const string event_full_circle = "CgkIm_nTr7sPEAIQAw"; // <GPGSID>
        public const string achievement_full_fleet = "CgkIm_nTr7sPEAIQBQ"; // <GPGSID>

}

